// Controlled vocabulary for species and breeds.
// Using fixed lists (instead of free text) is what lets the diagnosis /
// medication engine reliably match a patient to breed- and species-specific
// rules. This list is a starting point and will be expanded from the
// veterinary reference content later.

export const SPECIES: string[] = [
  'Dog',
  'Cat',
  'Rabbit',
  'Bird',
  'Horse',
  'Cattle',
  'Goat',
  'Sheep',
  'Guinea Pig',
  'Hamster',
  'Ferret',
  'Reptile',
  'Other',
];

export const BREEDS: Record<string, string[]> = {
  Dog: [
    'Labrador Retriever',
    'Golden Retriever',
    'German Shepherd',
    'French Bulldog',
    'Bulldog',
    'Poodle',
    'Beagle',
    'Rottweiler',
    'German Shorthaired Pointer',
    'Dachshund',
    'Pembroke Welsh Corgi',
    'Yorkshire Terrier',
    'Australian Shepherd',
    'Boxer',
    'Siberian Husky',
    'Cavalier King Charles Spaniel',
    'Great Dane',
    'Doberman Pinscher',
    'Shih Tzu',
    'Boston Terrier',
    'Bernese Mountain Dog',
    'Pomeranian',
    'Havanese',
    'Cane Corso',
    'Shetland Sheepdog',
    'Border Collie',
    'Chihuahua',
    'Pug',
    'Maltese',
    'Cocker Spaniel',
    'Mastiff',
    'Vizsla',
    'Weimaraner',
    'Collie',
    'Newfoundland',
    'Rhodesian Ridgeback',
    'Basset Hound',
    'Bichon Frise',
    'Akita',
    'Saint Bernard',
    'Bloodhound',
    'Jack Russell Terrier',
    'Whippet',
    'Papillon',
    'Samoyed',
    'Mixed breed',
  ],
  Cat: [
    'Domestic Shorthair',
    'Domestic Longhair',
    'Persian',
    'Maine Coon',
    'Siamese',
    'Ragdoll',
    'Bengal',
    'British Shorthair',
    'Sphynx',
    'Abyssinian',
    'Scottish Fold',
    'Russian Blue',
    'Norwegian Forest Cat',
    'American Shorthair',
    'Devon Rex',
    'Oriental Shorthair',
    'Birman',
    'Burmese',
    'Exotic Shorthair',
    'Himalayan',
    'Turkish Angora',
    'Savannah',
    'Tonkinese',
    'Cornish Rex',
    'Mixed breed',
  ],
  Rabbit: [
    'Holland Lop',
    'Netherland Dwarf',
    'Mini Rex',
    'Lionhead',
    'Flemish Giant',
    'Dutch',
    'English Lop',
    'Mini Lop',
    'Rex',
    'English Angora',
    'Mixed breed',
  ],
  Bird: [
    'Budgerigar',
    'Cockatiel',
    'African Grey Parrot',
    'Cockatoo',
    'Macaw',
    'Lovebird',
    'Canary',
    'Finch',
    'Conure',
    'Amazon Parrot',
    'Other',
  ],
  Horse: [
    'Thoroughbred',
    'Arabian',
    'Quarter Horse',
    'Appaloosa',
    'Warmblood',
    'Clydesdale',
    'Shetland Pony',
    'Friesian',
    'Morgan',
    'Mustang',
    'Other',
  ],
  Cattle: [
    'Holstein',
    'Jersey',
    'Angus',
    'Hereford',
    'Brahman',
    'Simmental',
    'Charolais',
    'Other',
  ],
  Goat: ['Boer', 'Nubian', 'Saanen', 'Alpine', 'Toggenburg', 'Pygmy', 'Other'],
  Sheep: ['Merino', 'Suffolk', 'Dorset', 'Romney', 'Corriedale', 'Other'],
  'Guinea Pig': ['American', 'Abyssinian', 'Peruvian', 'Teddy', 'Silkie', 'Other'],
  Hamster: ['Syrian', 'Dwarf Campbell', 'Winter White', 'Roborovski', 'Chinese', 'Other'],
  Ferret: ['Standard', 'Angora', 'Other'],
  Reptile: [
    'Bearded Dragon',
    'Leopard Gecko',
    'Ball Python',
    'Corn Snake',
    'Green Iguana',
    'Tortoise',
    'Turtle',
    'Other',
  ],
  Other: [],
};
